# Generated by Django 2.2.6 on 2019-10-30 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191030_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.Users', verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='main.Tags', verbose_name='Теги'),
        ),
    ]
