# Generated by Django 2.2.6 on 2019-10-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191030_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='views',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
