# Generated by Django 2.2.6 on 2019-12-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_tags_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='right_answer',
            field=models.BooleanField(default=False, verbose_name='верный ответ'),
        ),
    ]
