# Generated by Django 2.2.12 on 2020-04-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rewiew'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewiew',
            new_name='Rewiews',
        ),
    ]
