# Generated by Django 2.2.12 on 2020-04-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200420_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiews',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
