# Generated by Django 2.2.12 on 2020-04-20 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200420_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiews',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 21, 59, 31, 192892, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
