# Generated by Django 2.2.12 on 2020-04-20 22:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200420_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 22, 31, 18, 415386, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rewiews',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 22, 31, 18, 414829, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
