# Generated by Django 2.2.12 on 2020-04-20 22:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200420_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 22, 53, 39, 75044, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='number',
            field=models.CharField(default='Номер не указан.', max_length=30, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='usluga',
            field=models.CharField(choices=[('JR', 'Для юридических лиц'), ('PH', 'Для физических лиц')], default='PH', max_length=2, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='rewiews',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 22, 53, 39, 74609, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
