# Generated by Django 2.2.12 on 2020-04-21 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200420_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='author',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='author',
        ),
        migrations.AlterField(
            model_name='messages',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 12, 39, 13, 307666, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rewiews',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 12, 39, 13, 307177, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
